### ISSUE TITLE
requirement2 做歪了怎麼辦 在線等 急

### ISSUE THREAD

**Issue by tl455047** [aesophor/valkyrie#2]

**Comment by aesophor** [comment]
22576f563d1460b5ff1eeb8801e6c2a68136b4fe

**Comment by aesophor** [comment]
![mp4](https://user-images.githubusercontent.com/32998585/113261888-95f4d400-9302-11eb-9f5a-ce43925bb820.gif)

**Comment by a4865g** [comment]
![image](https://user-images.githubusercontent.com/43570004/113262035-ba50b080-9302-11eb-9671-ead6cacf4160.png)

**Comment by aesophor** [comment]
@a4865g 笑死 撥了啊 gogo

**Comment by a4865g** [comment]
@aesophor 出發 3 2 1 Brawl
